import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
// Generated by FlutterFire CLI (placeholder exists until you run it)
import 'package:gymmate/firebase_options.dart';

class FirebaseService {
  static Future<FirebaseApp> init() async {
    try {
      // Preferred: use generated options (web/desktop require this)
      final app = await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      await _ensureAnonymousAuth();
      return app;
    } on UnimplementedError catch (_) {
      // Fallback for Android/iOS when firebase_options.dart isn't generated yet
      final app = await Firebase.initializeApp();
      await _ensureAnonymousAuth();
      return app;
    } catch (e) {
      // Last resort: try default without options
      try {
        final app = await Firebase.initializeApp();
        await _ensureAnonymousAuth();
        return app;
      } catch (_) {
        rethrow;
      }
    }
  }

  static Future<void> _ensureAnonymousAuth() async {
    final auth = FirebaseAuth.instance;
    if (auth.currentUser == null) {
      await auth.signInAnonymously();
    }
  }
}
