import 'package:firebase_core/firebase_core.dart';
// Generated by FlutterFire CLI (placeholder exists until you run it)
import 'package:gymmate/firebase_options.dart';

class FirebaseService {
  static Future<FirebaseApp> init() async {
    try {
      // Preferred: use generated options (web/desktop require this)
      final app = await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      return app;
    } on UnimplementedError catch (_) {
      // Fallback for Android/iOS when firebase_options.dart isn't generated yet
      final app = await Firebase.initializeApp();
      return app;
    } catch (e) {
      // Last resort: try default without options
      try {
        final app = await Firebase.initializeApp();
        return app;
      } catch (_) {
        rethrow;
      }
    }
  }
}
